spring: 
  application: 
    name: spring-boot-admin-client
  boot: 
    admin: 
      url: http://localhost:8080
      username: user
      password: admin

server: 
  port: 8081

management: 
  security: 
    enabled: false
