server: 
  port: 8081

spring: 
  application: 
    name: spring-boot-admin-client
  boot: 
    admin: 
      url: http://spring-boot-admin
      username: user
      password: admin
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        instance-id: ${spring.application.name}:${random.value}
        health-check-interval: 5s
        health-check-critical-timeout: 1m
      enabled: true

management: 
  security: 
    enabled: false
