spring:
  cloud:
    consul:
      host: oasis.paulosalgado.xyz
      port: 8500
      discovery:
        enabled: true
        instance-id: ${spring.application.name}:${random.value}
        health-check-interval: 5s
        health-check-critical-timeout: 1m
      enabled: true
